# -*- coding: utf-8 -*-
"""Aula 09 - [G] - Desafio NExT Python - Dia 01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/DaniloRudrigues/6ce3a6dcfa50317ececfffe1fe6e08f3/aula-09-g-desafio-next-python-dia-01.ipynb

## PyFinanceiro

* Neste desafio, você tem a tarefa de criar um script Python para analisar os registros financeiros de sua empresa. Você fornecerá um conjunto de dados financeiros chamado [dados_financeiros.txt](https://drive.google.com/file/d/1g4A0DkMdGxwv9JSGO32DYqvPby45pIHG/view?usp=sharing). O conjunto de dados é composto por duas colunas: `Data` e `Lucros/Perdas`, separados por virgula. (Felizmente, sua empresa tem padrões bastante flexíveis para a contabilidade, então os registros são simples.)

* Sua tarefa é criar um script Python que analise os registros para calcular cada um das seguintes informações:

  * O número total de meses incluídos no conjunto de dados

  * O valor total líquido de "Lucros / Perdas" durante todo o período

  * A média dos "Lucros / Perdas" durante todo o período

  * A média das mudanças em "Lucros / Perdas" durante todo o período - OPCIONAL

  * O maior aumento nos lucros (data e valor) durante todo o período

  * A maior redução nas perdas (data e valor) ao longo de todo o período

* Por exemplo, sua análise deve ser semelhante a esta abaixo:

``` text
Analise financeira
----------------------------
Total de meses: 86
Total: $ 38382578
Média: $ 446309,04
Variação da média: $ -2315,12
Maior aumento nos lucros: fevereiro de 2012 ($ 1926159)
Maior redução nos lucros: setembro de 2013 ($ -2196167)
```

* Além disso, seu script final deve imprimir a análise no terminal e exportar um arquivo de texto `relatório.txt` com os resultados.
"""

from google.colab import drive
drive.mount('/content/drive')

arq = open('/content/drive/MyDrive/Colab Notebooks/dados_financeiro.txt','r')
A = arq.readline()
A = arq.read()
A = list(A.split('\n'))
AA = []
for i in range(len(A)):
  AA.append(A[i].split(','))
mes = []
din = []
for i in range(len(A)-1):
  mes.append(AA[i][0])
  din.append(AA[i][1])
for i in range(len(din)):
  din[i] = int(din[i])
arq.close()
import statistics
print('Analise financeira')
print('----------------------------')
print('Total de meses:',len(mes))
print('Total: $',sum(din))
print('Média: $ %.2f'%statistics.mean(din))
#print('Variação da média: $%.2f'%statistics.quantiles(din))
k = din.index(max(din))
print('Maior aumento nos lucros:',mes[k],'($ '+str(max(din))+')')
kk = din.index(min(din))
print('Maior redução nos lucros:',mes[kk],'($ '+str(min(din))+')')

"""## PyVotação

* Neste desafio, você tem a tarefa de ajudar uma pequena cidade rural a modernizar seu processo de contagem de votos. (Até agora, o tio Cleiton vinha contando-os um por um com confiança, mas, infelizmente, sua concentração não é o que costumava ser.)

* Você receberá um conjunto de dados de enquete chamado [dados_eleção.txt](https://drive.google.com/file/d/13tarkZMlfvMcHnS8K49pdF-GMYOwgggg/view?usp=sharing). O conjunto de dados é composto por três colunas: `ID do eleitor`,` Município` e `Candidato`. Sua tarefa é criar um script Python que analise os votos e calcule cada uma das seguintes informações:

  * O número total de votos expressos

  * Uma lista completa de candidatos que receberam votos

  * A porcentagem de votos que cada candidato ganhou

  * O número total de votos que cada candidato ganhou

  * O vencedor da eleição com base no voto popular.

* Por exemplo, sua análise deve ser semelhante a esta abaixo:

  ```text
  Resultados eleitorais
  -------------------------
  Total de votos: 3521001
  -------------------------
  Khan: 63.0% (2218231)
  Correy: 20.0% (704200)
  Li: 14.0% (492940)
  O'Tooley: 3.0% (105630)
  -------------------------
  Vencedor: Khan
  -------------------------
  ```

* Além disso, seu script final deve imprimir a análise no terminal e exportar um arquivo de texto `resultado.txt` com os resultados.
"""

arq = open('/content/drive/MyDrive/Colab Notebooks/dados_elecao.txt','r')
B = arq.readline()
B = arq.read()
B = list(B.split('\n'))
BB = []
for i in range(len(B)):
  BB.append(B[i].split(','))
ID = []
mun = []
cand = []
for i in range(len(B)-1):
  ID.append(BB[i][0])
  mun.append(BB[i][1])
  cand.append(BB[i][2])
arq.close()

print('Resultados eleitorais')
print('-------------------------')
print('Total de votos:',len(ID))
print('-------------------------')
per_khan = (cand.count('Khan')/len(ID))*100
print('Khan: %.1f'%per_khan,'% ('+str(cand.count('Khan'))+')')
per_Correy = (cand.count('Correy')/len(ID))*100
print('Correy: %.1f'%per_Correy,'% ('+str(cand.count('Correy'))+')')
per_Li = (cand.count('Li')/len(ID))*100
print('Li: %.1f'%per_Li,'% ('+str(cand.count('Li'))+')')
per_OTooley = (cand.count("O'Tooley")/len(ID))*100
print("O'Tooley: %.1f"%per_OTooley,'% ('+str(cand.count("O'Tooley"))+')')
print('-------------------------')
k  = [per_khan,per_Correy,per_Li,per_OTooley]
kk = ['Khan','Correy','Li',"O'Tooley"]
i = k.index(max(k))
print('Vencedor:', kk[i])
print('-------------------------')

arq2 = open('/content/drive/MyDrive/Colab Notebooks/resultado.txt','w')
arq2.write('Resultados eleitorais\n')
arq2.write('-------------------------\n')
arq2.write('Total de votos: '+str(len(ID))+'\n')
arq2.write('-------------------------\n')
arq2.write('Khan: %.1f'%per_khan+'% ('+str(cand.count('Khan'))+')\n')
arq2.write('Correy: %.1f'%per_Correy+'% ('+str(cand.count('Correy'))+')\n')
arq2.write('Li: %.1f'%per_Li+'% ('+str(cand.count('Li'))+')\n')
arq2.write("O'Tooley: %.1f"%per_OTooley+'% ('+str(cand.count("O'Tooley"))+')\n')
arq2.write('-------------------------\n')
arq2.write('Vencedor: '+kk[i]+'\n')
arq2.write('-------------------------\n')
arq2.close()