# -*- coding: utf-8 -*-
"""Aula 02 - [G] - Operadores Lógicos e Estrutura Condicional.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uvXNjHH1dUGKDFEWm7Az_HphmTn4yu5D

# Exercícios

1. Informe a saída das seguintes expressões:

a)
```python
3 < 8 # True
```
b)
```python
a = 12
b = a - 10
a > b
```
c)
```python
16 != 16
```
d)
```python
2 < 5 > 10
```
e)
```python
3 <= 5 >= 2
```
"""

#A)
print(3 < 8)
#B)
a=12
b=a-10
print(a > b)
#C)
print(16 != 16)
#D)
print(2 < 5 > 10)
#E)
print(3 <= 5 >= 2)

"""2. Verifique se as igualdades abaixo são verdadeiras:

**(a)** $2 \times 2.0 = 4$
"""

print(2*2.0 == 4)

"""**(b)** $2 \times 3 = 5$"""

print(2*3 == 5)

"""**(c)** $4a + 3 = b$, para $a=3$ e $b=15$ (primeiro declare as variáveis `a` e `b`)"""

a = 3
b = 15
print(4*a + 3 == b)

"""3. Faça um programa que calcule as raízes de uma equação do segundo grau, na forma `ax² + bx + c`. O programa deverá pedir os valores de a, b e c e fazer as consistências, informando ao usuário nas seguintes situações:

a - Se o usuário informar o valor de A igual a zero, a equação não é do segundo grau e o programa não deve pedir os demais valores, sendo encerrado;

b - Se o delta calculado for negativo, a equação não possui raizes reais. Informe ao usuário e encerre o programa;

c - Se o delta calculado for igual a zero a equação possui apenas uma raiz real; informe-a ao usuário;

d - Se o delta for positivo, a equação possui duas raiz reais; informe-as ao usuário;
"""

a = float(input("Digite o valor da constante (a) para uma função de 2° grau: "))
if a != 0:
  b = float(input("Digite o valor da constante (b) para uma função de 2° grau: "))
  c = float(input("Digite o valor da constante (c) para uma função de 2° grau: "))

  delta = b**2-4*a*c

  if delta < 0:
    print("A equação não possui raizes reais")
  elif delta == 0:
    x0 = (-b)/2*a
    print("A equação possui apenas uma raiz real que é:",x0)
  else:
    x1 = (-b+(delta**(0.5)))/2*a
    x2 = (-b-(delta**(0.5)))/2*a
    print("A equação possui duas raiz reais que são:",x1 ,"e ", x2)

else:
  print('a equação não é do segundo grau - PROGRAMA ENCERRADO')

"""4. Faça um Programa que peça um número correspondente a um determinado ano e em seguida informe se este ano é ou não bissexto."""

ano = int(input("Digite o ano: "))
resto = ano % 4
if resto == 0:
  print("o ano de",ano ,"é bissexto")
else:
  print("o ano de",ano ,"NÃO é bissexto")

"""5. Faça um Programa que peça uma data no formato dd/mm/aaaa e determine se a mesma é uma data válida."""

print("Digite uma data no formato dd/mm/aaaa")
dia = int(input("Primeiro, digite o dia (valores entre 1 à 31):"))
mes = int(input("Em seguida, digite o mês (valores entre 1 à 12):"))
ano = int(input("Por fim, digite o ano:"))

resto = ano % 4

if resto == 0:
  if mes==1 or mes==3 or mes==5 or mes==7 or mes==8 or mes==10 or mes==12:
    if dia >= 1 and dia <= 31:
      print(dia,"/",mes,"/",ano)
    else:
      print("O dia da data está fora dos padrões")
  elif mes==2:
    if dia >= 1 and dia <= 29:
      print(dia,"/",mes,"/",ano)
    else:
      print("O dia da data está fora dos padrões")
  elif mes==4 or mes==6 or mes==9 or mes==11:
    if dia >= 1 and dia <= 30:
      print(dia,"/",mes,"/",ano)
    else:
      print("O dia da data está fora dos padrões")
  else:
    print("O mês da data está fora dos padrões")
else:
  if mes==1 or mes==3 or mes==5 or mes==7 or mes==8 or mes==10 or mes==12:
    if dia >= 1 and dia <= 31:
      print(dia,"/",mes,"/",ano)
    else:
      print("O dia da data está fora dos padrões")
  elif mes==2:
    if dia >= 1 and dia <= 28:
      print(dia,"/",mes,"/",ano)
    else:
      print("O dia da data está fora dos padrões, o ano não é bissexto")
  elif mes==4 or mes==6 or mes==9 or mes==11:
    if dia >= 1 and dia <= 30:
      print(dia,"/",mes,"/",ano)
    else:
      print("O dia da data está fora dos padrões")
  else:
    print("O mês da data está fora dos padrões")

"""6. Faça um Programa que leia um número e exiba o dia correspondente da semana. (1-Domingo, 2- Segunda, etc.), se digitar outro valor deve aparecer valor inválido."""

var1 = int(input('Digite a um número de 1 a 7 para receber um dia da semana: '))

var2 = ['DOMINGO','SEGUNDA','TERÇA','QUARTA','QUINTA','SEXTA','SÁBADO']
print(var2[var1 - 1])

"""7. Crie um programa para um circo, no qual dada a idade de uma pessoa, seja indicado o valor do ingresso segundo as regras:

a) A entrada para qualquer pessoa com menos de 4 anos ou maior que 60 é gratuita;

b) a entrada para qualquer pessoa com idade entre 4 e 18 custa 20 reais;

c) a entrada para qualquer pessoa com 18 ou mais custa 30 reais;

d) estudantes e professores pagam meia-entrada.
"""

var1 = str(input('Deseja ingresso para estudante ou professor, se sim digite "s", se não digite "n": '))

# garantia de sim ou não
while var1 != 's' and var1 != 'n':
  print('Valor inválido. tente novamente')
  var1 = str(input('Deseja ingresso para estudante ou professor, se sim digite "s", se não digite "n": '))

var2 = int(input('Qual a sua idade? '))
# cálculo do ingresso
if var1 == 'n':
  if var2 <= 4 or var2 >= 60:
    print('Entrada Gratuita')
  elif var2 > 4 and var2 <= 18:
    print('Entrada custa R$ 20.00')
  else:
    print('Entrada custa R$ 30.00')
else:
  if var2 <= 4 or var2 >= 60:
    print('Entrada Gratuita')
  elif var2 > 4 and var2 <= 18:
    print('Entrada custa R$ 10.00')
  else:
    print('Entrada custa R$ 15.00')

"""8. Complete o código na célula abaixo para imprimir uma mensagem informando se um aluno foi aprovado ou reprovado em uma disciplina com base em sua nota final. A nota mínima necessária para aprovação é  5 ."""

nota = float(input('Digite a nota final do aluno: '))
if nota >= 5 and nota <= 10:
  print('Aluno Aprovado')
elif nota >=0 and nota < 5:
  print('Aluno Reprovado')
else:
  print('Nota inválida')

"""9. Construa uma pequena **chave dicotômica** para identificar uma determinada planta como membro de um dos principais grupos: *Bryophyta*, *Pteridophyta*, *Gymnospermae* ou *Angiospermae*.
A identificação se dá com base na presença (1) ou ausência (0) de três caracteres: **vascularização**, **sementes** e **flores**. 
Utilize a tabela abaixo como referência.

| Grupo | Vascularização| Sementes| Flores |
|--|--|--|--|
| Bryophyta | 0 | 0 | 0 |
| Pteridophyta | 1| 0 | 0 |
| Gymnospermae | 1 | 1 | 0 |
| Angiospermae | 1 | 1 | 1 |
"""

# Estas variáveis armazenam a presença (1) ou ausência (0) de cada caractere
vasc = 1
sem = 0
flor = 0

# Seu código aqui
if vasc == 0 and sem == 0 and flor == 0:
  print('A espécie é Bryophyta')
elif  vasc == 1 and sem == 0 and flor == 0:
  print('A espécie é Pteridophyta')
elif  vasc == 1 and sem == 1 and flor == 0:
  print('A espécie é Gymnospermae')
elif  vasc == 1 and sem == 1 and flor == 1:
  print('A espécie é Gymnospermae')
else:
  print('Espécie não cadastrada')

"""10. Um posto está vendendo combustíveis com a seguinte tabela de descontos:

a. Álcool:

    até 20 litros, desconto de 3% por litro
    acima de 20 litros, desconto de 5% por litro

b. Gasolina:

    até 20 litros, desconto de 4% por litro
    acima de 20 litros, desconto de 6% por litro

Escreva um algoritmo que leia o número de litros vendidos, o tipo de combustível (codificado da seguinte forma: A-álcool, G-gasolina), calcule e imprima o valor a ser pago pelo cliente sabendo-se que o preço do litro da gasolina é 2.50 o preço do litro do álcool é 1,90.
"""

t = str(input('Digite o tipo de combistível utilizado "A" para álcool ou "G" para gasolina: '))
while  t != "A" and t != "a" and t != "G" and t != "g":
  print('Código digitado inválido. Tente novamente.')
  t = str(input('Digite o tipo de combistível utilizado "A" para álcool ou "G" para gasolina: '))

vol = float(input('Digite o volume consumido de combustível (em litros): '))
while vol < 0:
  print('Volume negativo. Tente novamente.')
  vol = float(input('Digite o volume consumido de combustível (em litros): '))

ap = 1.90
gp = 2.50

if t == 'a' or t == 'A':
  if vol <= 20:
    des1 = 1-0.03
    var1 = float(round(des1 * vol * ap,2))
    print('o preço é R$',var1)
  else:
    des2 = 1-0.05
    var2 = float(round(des2 * vol * ap,2))
    print('o preço é R$',var2)
else:
  if vol <= 20:
    des3 = 1-0.04
    var3 = float(round(des3 * vol * gp,2))
    print('o preço é R$',var3)
  else:
    des4 = 1-0.06
    var4 = float(round(des4 * vol * gp,2))
    print('o preço é R$',var4)

"""11. Faça um Programa que leia 2 números e em seguida pergunte ao usuário qual operação ele deseja realizar. O resultado da operação deve ser acompanhado de uma frase que diga se o número é:

a. par ou ímpar;

b. positivo ou negativo;

c. inteiro ou decimal.
"""

a = float(input('Digite um número: '))
b = float(input('Digite um número: '))
print()
print('Qual a operação será escolhida:')
print('   "+" para SOMA')
print('   "-" para SUBTRAÇÃO')
print('   "*" para MULTIPLICAÇÃO')
print('   "/" para DIVISÃO')
print('   "**" para POTENCIAÇÃO')
op = str(input('Qual a opção escolhida: '))

while op != "+" and op != "-" and op != "*" and op != "/" and op != "**":
  print('Escolha inválida. Tente novamente')
  op = str(input('Qual a opção escolhida: '))

if op == "+":
  c = a + b
  if c % 2 == 0:
    poui = 'PAR'
  else:
    poui = 'IMPAR'
  if c >= 0:
    poun = 'POSITIVO'
  else:
    poun = 'NEGATIVO'
  if c - round(c) == 0:
    tip = 'INTEIRO'
  else:
      tip = 'DECIMAL'
  print('O resultado é',c,'que é um valor',poui,',',poun,'e',tip)
elif op == '-':
  c = a - b
  if c % 2 == 0:
    poui = 'PAR'
  else:
    poui = 'IMPAR'
  if c >= 0:
    poun = 'POSITIVO'
  else:
    poun = 'NEGATIVO'
  if c - round(c) == 0:
    tip = 'INTEIRO'
  else:
    tip = 'DECIMAL'
  print('O resultado é',c,'que é um valor',poui,',',poun,'e',tip)
elif op == '*':
  c = a * b
  if c % 2 == 0:
    poui = 'PAR'
  else:
    poui = 'IMPAR'
  if c >= 0:
    poun = 'POSITIVO'
  else:
    poun = 'NEGATIVO'
  if c - round(c) == 0:
    tip = 'INTEIRO'
  else:
    tip = 'DECIMAL'
  print('O resultado é',c,'que é um valor',poui,',',poun,'e',tip)
elif op == '/':
  c = a / b
  if c % 2 == 0:
    poui = 'PAR'
  else:
    poui = 'IMPAR'
  if c >= 0:
    poun = 'POSITIVO'
  else:
    poun = 'NEGATIVO'
  if c - round(c) == 0:
    tip = 'INTEIRO'
  else:
    tip = 'DECIMAL'
  print('O resultado é',c,'que é um valor',poui,',',poun,'e',tip)
else:
  c = a ** b
  if c % 2 == 0:
    poui = 'PAR'
  else:
    poui = 'IMPAR'
  if c >= 0:
    poun = 'POSITIVO'
  else:
    poun = 'NEGATIVO'
  if c - round(c) == 0:
    tip = 'INTEIRO'
  else:
    tip = 'DECIMAL'
  print('O resultado é',c,'que é um valor',poui,',',poun,'e',tip)