# -*- coding: utf-8 -*-
"""Aula 03 - [G] - Strings.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/DaniloRudrigues/e22e8728e140e6cd05f93d79bac349c3/aula-03-g-strings.ipynb

# Exercícios Fundamentais

1. Faça um programa que leia uma string e a imprima.
"""

var1 = str(input('Escreva qualquer coisa: '))
print(var1)

"""2. Crie um programa que imprima o comprimento de uma string."""

var1 = 'Danilo Rudrigues de Almeida Lira'
print(len(var1))

"""3. Crie um programa que compara duas strings."""

# python é igual python ?
var1 = 'Danilo Rudrigues de Almeida Lira'
var2 = 'asdfa asdfasde ewerwef jsdsjdf'

var3 = 'asdasd'
var4 = 'aaaaaa'

var5 = 'igual'
var6 = 'igual'

print(var1 == var2)
print(var3 == var4)
print(var5 == var6)

"""4. Faça um programa que leia um nome e imprima as 4 primeiras letras do nome."""

# python -> pyth
var1 = str(input('Escreva qualquer coisa: '))
var2 = ''
for k in range(4):
  var2 += var1[k]
print(var2)

"""5. Escreva um programa que substitui as ocorrencias de um caractere 0 em uma string por outro caractere 1."""

# 010101 -> 111111
var1 = '010101'
var2 = var1.replace('0','1')
print(var2)

"""6. Entre com um nome e imprima o nome somente se a primeira letra do nome for “a” (maiuscula ou minuscula)."""

var1 = str(input('Escreva qualquer coisa: '))
if var1[0] == "a" or var1[0] == "A":
  print(var1)

"""7. Faça um programa que receba do usuario uma string. O programa imprime a string sem suas vogais."""

var1 = str(input('Escreva qualquer coisa: '))
k = 'aAeEiIoOuU'
for ks in k:
  var1 = var1.replace(ks,'')
print(var1)

"""8. Faça um programa em que troque todas as ocorrencias de uma letra L1 pela letra L2 em uma string. A string e as letras L1 e L2 devem ser fornecidas pelo usuario."""

var1 = str(input('Escreva qualquer coisa: '))

L1 = str(input('Escreva uma letra coisa: '))
while len(L1) >= 2:
  print('você escreveu mais de um caractere. Tente novamente.')
  L1 = str(input('Escreva uma letra coisa: '))

L2 = str(input('Escreva outra letra coisa: '))
while len(L2) >= 2:
  print('você escreveu mais de um caractere. Tente novamente.')
  L2 = str(input('Escreva outra letra coisa: '))

print(var1.replace(L1,L2))

"""# Exercícios de Aprofundamento

1. Faça um programa para converter uma letra maiuscula em letra minuscula. Use a tabela ASCII para resolver o problema.
"""

mai = 'A'
print(chr(ord(mai)+32))

"""2. Ler nome, sexo e idade. Se sexo for feminino e idade menor que 25, imprime o nome da pessoa e a palavra “ACEITA”, caso contrario imprimir “NÃO ACEITA”."""

nome = str(input('Escreva o nome: '))
sexo = str(input('Qual o sexo, se masculino digite "m", se feminino digite "f": '))
while sexo != "m" and sexo != "M" and sexo != "f" and sexo != "F":
  print('Valor Inválido. Tente novamente.')
  sexo = str(input('Qual o sexo, se masculino digite "m", se feminino digite "f": '))
ida = int(input('Qual a idade?'))
while ida < 0:
  print('Valor Inválido. Idade negativa... Tente novamente.')
  ida = int(input('Qual a idade? '))
if sexo == 'f' or sexo == 'F' and ida < 25:
  print(nome, 'foi ACEITA')
else:
  print(nome, ' NÃO ACEITA')

"""3. Faça um programa que conte o numero de 1's que aparecem em um string. Exemplo: 

0011001 -> 3
"""

var1 = '0011001'

var2 = var1.replace('1','')
A = len(var1)
B = len(var2)

print(A-B)

"""4. Faça um programa que receba uma palavra e a imprima de tras-para-frente."""

var1 = str(input('Escreva qualquer coisa: '))
print(var1[::-1])

"""5. Faça um programa que receba uma palavra e calcule quantas vogais (a, e, i, o, u) possui essa palavra. Entre com um caractere (vogal ou consoante) e substitua todas as vogais da palavra dada por esse caractere."""

var1 = str(input('Escreva qualquer coisa: '))

vog = 'AaEeIiOoUu'
var2 = var1
for k in vog:
  var2 = var2.replace(k,'')
qvo = len(var1) - len(var2)
print('O número de vogias é ',qvo)

car = str(input('Escreva um caractere (vogal ou consoante): '))
while len(car) > 1:
  print('Mais de um caratere. tente de novo.')
  car = str(input('Escreva um caractere (vogal ou consoante): '))

var3 = var1
for t in vog:
  var3 = var3.replace(t,car)
print(var3)

"""6. Ler uma frase e contar quantos caracteres sao brancos. Lembre-se que uma frase e um conjunto de caracteres (vetor)."""

var1 = str(input('Escreva uma frase: '))

var2 = var1.split(' ')
var3 = ''
for k in range(len(var2)):
  var3 += var2[k]
print()
print('A quantidade de espaços é ',len(var1)-len(var3))

"""7. Faça um programa que leia uma palavra e some 1 no valor ASCII de cada caractere da
palavra. Imprima a string resultante.
"""

var1 = str(input('Esvreva uma palavra: '))

var2 = list(range(len(var1)))
for k in range(len(var1)):
  var2[k] = var1[k]

var3 = ''
for k in range(len(var1)):
  var3 += chr(ord(var2[k])+1)

print(var3)

"""8. Leia uma cadeia de caracteres e converta todos os caracteres para maiuscula. 
Dica:
subtraia 32 dos caracteres cujo codigo ASCII esta entre 65 e 90. 
"""

var1 = str(input('Escreva qualquer coisa: '))

# ---Método 1---
print()
print('método 1:')
print(var1.upper())



#---Método 2---
print()
var2 = ''
for k in range(len(var1)):
  if ord(var1[k]) >= 97 and  ord(var1[k])<= 122:
    var2 += chr(ord(var1[k])-32)
  else:
    var2 += var1[k]
print('método 2:')
print(var2)

"""9. Escreva um programa para converter uma cadeia de caracteres de letras maiusculas em letras minusculas."""

var1 = str(input('Escreva qualquer coisa: '))

# ---Método 1---
print()
print('método 1:')
print(var1.lower())



#---Método 2---
print()
var2 = ''
for k in range(len(var1)):
  if ord(var1[k]) >= 65 and  ord(var1[k])<= 90:
    var2 += chr(ord(var1[k])+32)
  else:
    var2 += var1[k]
print('método 2:')
print(var2)

"""10. Leia um vetor contendo letras de uma frase inclusive os espaços em branco. Retirar os espaços em branco do vetor e depois escrever o vetor resultante."""

var1 = str(input('Escreva uma frase: '))

var2 = var1.split(' ')
var3 = ''
for k in range(len(var2)):
  var3 += var2[k]

print()
print('A frase sem espaços é: ')
print(var3)

"""11. Escreva um programa que verifique se determinada entrada de usuário é um número. Considere válido números interios e reais, positivos e negativos, como: `10`, `-20`, `103.0`, `-12.5`"""

var1 = str(input('Escreva qualquer coisa: '))

try:
  float(var1)
  print('O dado digitado é um número.')
except:
  print('O dado digitado NÃO é um número.')